### ISSUE TITLE
A few bugs in ch03: softmax_model_loader_1.py

### ISSUE THREAD

**Issue by prakharchoudhary** [PacktPublishing/Deep-Learning-with-TensorFlow#3]
In the python 2.7 directory of ch03; a few bugs can be found for `softmax_model_loader_1.py`:
1. While the image is stored in a variable names `img`:
`line 17: img = mnist.test.images[num]`
The variable referenced while plotting it is `image_b`:
`line 23: plt.imshow(image_b.reshape([28, 28]), cmap='Greys')`

2. `In line 19`, img passed in the feed_dict has shape (784,) however the expected shape is (1,784).
3. `In line 21`, `result` is an array comprised of 2 other arrays, out of which the second array has the prediction probability for every character hence, the results should be printed as:
`line 20: print(result[1])`
`line 21: print(sess.run(tf.argmax(result[1], 1)))`

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
