### ISSUE TITLE
Performance issue in the Chapter04/EMOTION_CNN/Python%203.5/test_your_image.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [PacktPublishing/Deep-Learning-with-TensorFlow#8]
Hello, I found a performance issue in the Chapter04/EMOTION_CNN/Python%203.5/test_your_image.py, [`tf.argmax(result, 1)`](https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow/blob/fc63d61ddb7f032fb3772d4c9a48f5ae04717fce/Chapter04/EMOTION_CNN/Python%203.5/test_your_image.py#L63) will be created repeatedly during program execution, resulting in reduced efficiency. I think `result` and `tf.argmax(result, 1)` should be created before the loop.

The same issue exists in :

- [tf.argmax(result, 1) in Chapter04/EMOTION_CNN/Python 2.7/test_your_image.py](https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow/blob/fc63d61ddb7f032fb3772d4c9a48f5ae04717fce/Chapter04/EMOTION_CNN/Python%202.7/test_your_image.py#L63)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by sonam-packt** [comment]
Hi @DLPerf,

Thank you for your message.

Here is the link to the latest edition of the book, you can check it out: https://www.packtpub.com/product/deep-learning-with-tensorflow-2-and-keras-second-edition/9781838823412

Thank you!
